name: WorldProtection
version: ${projectVersion}
main: net.qilla.worldprotection.WorldProtection
api-version: '1.20'
load: STARTUP
commands:
  plugins:
    description: Returns the server's current plugin list.
    usage: /plugins
    aliases: [pl]